name: Publish Docker
on:
  push:
    branches:
      - ver/1.8.8
jobs:
  push:
    name: Push image to registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Push to registry
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: ProjectKig/KigPaper/kig-paper
          tag_with_ref: true